### ISSUE TITLE
开源吧，开源内核吧

### ISSUE THREAD

**Issue by ghost** [meizuosc/meizuosc.github.io#8]
flyme8根本不知道出不出，更不更新底层，又不开源，你是要用户一直用7.1？8.1？，不更新不说别的，老系统还有bug，到底是想咋整，我就想不懂，以前遵守开源协议，现在怎么根本就不遵守，连oppo这种以前不能解锁BootLoader不开源的厂商，现在都变了，开始开源开放bl，你就为了查找手机，安卓系统你根本做不到百分百安全，你不开源你起码把你官方系统优化好行吧，一直不更新，安全补丁还是3月的，是要闹哪样？你自己flyme7上写的安全补丁解决安全漏洞，怎么现在不重视了，我问你们工程师，你flyme版本没新版本就不更新补丁，哪家是你这样子的。人更新速度快的厂商，都是老早准备新版本，就等谷歌的补丁，你们呢，谷歌补丁早就有了，新版本毛都没有。还有个底层，是不是真的要通过买新机才能更新底层。麻烦速度加快点行不行，你bug修复给力点成不，有些bug很长一段时间还存在，实在不行你就开源。真是无语，一锤子买卖吗

**Comment by Droid-MAX** [comment]
等你手上的手机完全淘汰沦为废品时，他们也许就会考虑开源内核代码了
